### ISSUE TITLE
from Webull import Webull?

### ISSUE THREAD

**Issue by nawihu** [asayadi/Webull-Trading-Bot#2]
What is this Webull module you try to import?  Is it just something unfinished, or in a different repo?

**Comment by asayadi** [comment]
Webull is a stock trading exchange, if you have an account you can use this Webull API to connect to your account and perform actions such as placing trades.

**Comment by nawihu** [comment]
> Webull is a stock trading exchange, if you have an account you can use this Webull API to connect to your account and perform actions such as placing trades.

Right, but in the documentation you mention that this program has a bot that will automate trades.  I don't see any part of the code that would do such a thing?  You import a "webull class"  but there is no module/class named "webull"

**Comment by asayadi** [comment]
The automation would be utilizing the scraped data from the discord program and parsing the text for what you are looking for and then feeding it into the Webull program. Those parts are not in the code because it would vary based on what you are doing exactly and what the format of the servers you are scraping are, as well as the type of trades you are doing (options/shares). The code for scraping is built for you, as well as to authenticate with Webull. All you need to do is make an algorithm to accurately parse the messages from a signal server and then feed that into a Webull API call for whatever trade you want to do. That Webull API is public, you can google it and find its methods so you can make the call. Hope this helps
